# Generated by Django 4.2.20 on 2025-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='split_ratio',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
