# Generated by Django 4.2.20 on 2025-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_transaction_split_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_per_share',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
